import Head from "next/head";
import { GetServerSideProps } from "next";

interface PageProps {
    foo: string;
}

export default function Home({ foo }: PageProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                {"Ola criancada!!!!!!!!!!!!!!!!"}
            </div>
        </>
    );
}

export const getServerSideProps: GetServerSideProps<PageProps> = async () => {
    return { props: { foo: "" } };
};
